class Friend {
  const Friend({
    required this.firstName,
    required this.lastName,
    required this.image,
    required this.upi,
    required this.exchanges,
    required this.paybacks,
    required this.dues,
    required this.days,
    required this.amount,
  });

  final String firstName;
  final String lastName;
  final String image;
  final String upi;
  final String exchanges;
  final String paybacks;
  final String dues;
  final String days;
  final String amount;
}

class Friends {
  final List<Friend> _recent = [
    Friend(
      firstName: 'Sukhshagar',
      lastName: 'Acharya',
      image: '',
      upi: 'sukhshagar@oksbi',
      exchanges: '18k',
      paybacks: '234',
      dues: '123',
      days: '3',
      amount: '3,456',
    ),
    Friend(
      firstName: 'McDonalds',
      lastName: '',
      image: 'assets/images/recent/mcdonalds.png',
      upi: 'mcdonalds@okhdfc',
      exchanges: '4.5k',
      paybacks: '432',
      dues: '476',
      days: '5',
      amount: '4,567',
    ),
    Friend(
      firstName: 'Harender',
      lastName: 'Khatri',
      image: 'assets/images/recent/harender.png',
      upi: 'harenderkhatri@okhdfc',
      exchanges: '1.2k',
      paybacks: '453',
      dues: '324',
      days: '7',
      amount: '45,678',
    ),
    Friend(
      firstName: 'Harol',
      lastName: 'Ahuja',
      image: 'assets/images/recent/harol.png',
      upi: 'harolahuja@okhdfc',
      exchanges: '8.7k',
      paybacks: '567',
      dues: '432',
      days: '5',
      amount: '4,356',
    ),
    Friend(
      firstName: 'Malli',
      lastName: 'Anand',
      image: 'assets/images/recent/malli.png',
      upi: 'mallianand@okaxis',
      exchanges: '567',
      paybacks: '335',
      dues: '375',
      days: '8',
      amount: '5,435',
    ),
    Friend(
      firstName: 'Red DP',
      lastName: 'Laghari',
      image: 'assets/images/recent/reddp.png',
      upi: 'reddplaghari@okaxis',
      exchanges: '3.4k',
      paybacks: '454',
      dues: '875',
      days: '2',
      amount: '6,456',
    ),
    Friend(
      firstName: 'Saksha',
      lastName: 'Patel',
      image: 'assets/images/recent/saksha.png',
      upi: 'sakshapatel@okhdfc',
      exchanges: '3.4k',
      paybacks: '765',
      dues: '987',
      days: '4',
      amount: '1,234',
    ),
    Friend(
      firstName: 'Sakshi',
      lastName: 'Reddy',
      image: 'assets/images/recent/sakshi.png',
      upi: 'sakshireddy@oksbi',
      exchanges: '5.6k',
      paybacks: '456',
      dues: '876',
      days: '6',
      amount: '4,567',
    ),
    Friend(
      firstName: 'Sampreet',
      lastName: 'Bakshi',
      image: 'assets/images/recent/sampreet.png',
      upi: 'sampreetbakshi@oksbi',
      exchanges: '567',
      paybacks: '765',
      dues: '343',
      days: '1',
      amount: '2,345',
    ),
    Friend(
      firstName: 'John',
      lastName: 'Anthony',
      image: 'assets/images/recent/john1.png',
      upi: 'johnanthony@okaxis',
      exchanges: '2.1k',
      paybacks: '675',
      dues: '453',
      days: '3',
      amount: '1,234',
    ),
    Friend(
      firstName: 'Suresh',
      lastName: 'Babu',
      image: 'assets/images/recent/suresh.png',
      upi: 'sureshbabu@oksbi',
      exchanges: '2.4k',
      paybacks: '455',
      dues: '765',
      days: '5',
      amount: '234',
    ),
    Friend(
      firstName: 'Ramesh',
      lastName: 'Arya',
      image: 'assets/images/recent/ramesh.png',
      upi: 'ramesharya@okhdfc',
      exchanges: '567',
      paybacks: '343',
      dues: '765',
      days: '4',
      amount: '3,333',
    ),
    Friend(
      firstName: 'Mukesh',
      lastName: 'Balakrishnan',
      image: 'assets/images/recent/mukesh.png',
      upi: 'mukeshbalakrishnan@okhdfc',
      exchanges: '3.5k',
      paybacks: '456',
      dues: '234',
      days: '4',
      amount: '5,678',
    ),
    Friend(
      firstName: 'Manish',
      lastName: 'Banerjee',
      image: 'assets/images/recent/manish.png',
      upi: 'manishbanerjee@okaxis',
      exchanges: '345',
      paybacks: '456',
      dues: '765',
      days: '3',
      amount: '5,467',
    ),
    Friend(
      firstName: 'Prakash',
      lastName: 'Burman',
      image: 'assets/images/recent/prakash.png',
      upi: 'prakashburman@okhdfc',
      exchanges: '2.4k',
      paybacks: '543',
      dues: '573',
      days: '6',
      amount: '2,345',
    ),
    Friend(
      firstName: 'Rakesh',
      lastName: 'Bhatt',
      image: 'assets/images/recent/rakesh.png',
      upi: 'rakeshbhatt@oksbi',
      exchanges: '6.4k',
      paybacks: '645',
      dues: '233',
      days: '2',
      amount: '4,567',
    ),
    Friend(
      firstName: 'Mukesh',
      lastName: 'Basu',
      image: 'assets/images/recent/mukesh1.png',
      upi: 'mukeshbasu@okaxis',
      exchanges: '5.6k',
      paybacks: '334',
      dues: '654',
      days: '5',
      amount: '3,456',
    ),
    Friend(
      firstName: 'Macander',
      lastName: 'Bedi',
      image: 'assets/images/recent/macander.png',
      upi: 'macanderbedi@okhdfc',
      exchanges: '4.3k',
      paybacks: '542',
      dues: '678',
      days: '4',
      amount: '2,456',
    ),
    Friend(
      firstName: 'David',
      lastName: 'Varma',
      image: 'assets/images/recent/david.png',
      upi: 'davidvarma@oksbi',
      exchanges: '567',
      paybacks: '256',
      dues: '234',
      days: '1',
      amount: '5,467',
    ),
    Friend(
      firstName: 'Malli',
      lastName: 'Dara',
      image: 'assets/images/recent/malli1.png',
      upi: 'mallidara@oksbi',
      exchanges: '234',
      paybacks: '567',
      dues: '344',
      days: '4',
      amount: '234',
    ),
    Friend(
      firstName: 'Adam',
      lastName: 'Dalal',
      image: '',
      upi: 'adamdalal@okhdfc',
      exchanges: '345',
      paybacks: '445',
      dues: '476',
      days: '2',
      amount: '655',
    ),
    Friend(
      firstName: 'Apple',
      lastName: 'Chowdhury',
      image: 'assets/images/recent/apple.png',
      upi: 'applechowdhury@okaxis',
      exchanges: '467',
      paybacks: '754',
      dues: '643',
      days: '4',
      amount: '346',
    ),
    Friend(
      firstName: 'Ball',
      lastName: 'Chabra',
      image: 'assets/images/recent/ball.png',
      upi: 'ballchabra@oksbi',
      exchanges: '543',
      paybacks: '435',
      dues: '765',
      days: '3',
      amount: '567',
    ),
    Friend(
      firstName: 'Cat',
      lastName: 'Chadha',
      image: 'assets/images/recent/cat.png',
      upi: 'catchadha@oksbi',
      exchanges: '345',
      paybacks: '567',
      dues: '322',
      days: '7',
      amount: '235',
    ),
    Friend(
      firstName: 'Dog',
      lastName: 'Chakrabarti',
      image: 'assets/images/recent/dog.png',
      upi: 'dogchakrabarti@okhdfc',
      exchanges: '345',
      paybacks: '432',
      dues: '543',
      days: '6',
      amount: '346',
    ),
  ];

  List<Friend> _frequent = [
    Friend(
      firstName: 'Harshada',
      lastName: 'Nikam',
      image: 'assets/images/frequent/harshada1.png',
      upi: 'harshadanikam-1@okhdfc',
      exchanges: '19k',
      paybacks: '983',
      dues: '123',
      days: '4',
      amount: '334',
    ),
    Friend(
      firstName: 'Naveen',
      lastName: 'Ahluwalia',
      image: 'assets/images/frequent/naveen.png',
      upi: 'neveenahluwalia@okhdfc',
      exchanges: '324',
      paybacks: '435',
      dues: '321',
      days: '5',
      amount: '876',
    ),
    Friend(
      firstName: 'Vivek',
      lastName: 'Amin',
      image: 'assets/images/frequent/vivek.png',
      upi: 'vivekamin@oksbi',
      exchanges: '342',
      paybacks: '232',
      dues: '654',
      days: '2',
      amount: '331',
    ),
    Friend(
      firstName: 'Rahul',
      lastName: 'Apte',
      image: 'assets/images/frequent/rahul.png',
      upi: 'rahulapte@oksbi',
      exchanges: '342',
      paybacks: '533',
      dues: '654',
      days: '6',
      amount: '235',
    ),
    Friend(
      firstName: 'Naveepriya',
      lastName: 'Datta',
      image: 'assets/images/frequent/naveepriya.png',
      upi: 'naveenpriyadatta@oksbi',
      exchanges: '342',
      paybacks: '545',
      dues: '534',
      days: '5',
      amount: '422',
    ),
    Friend(
      firstName: 'Subhash',
      lastName: 'Deol',
      image: 'assets/images/frequent/subhash.png',
      upi: 'subhashdeol@okaxis',
      exchanges: '234',
      paybacks: '343',
      dues: '245',
      days: '4',
      amount: '422',
    ),
    Friend(
      firstName: 'Ramshankar',
      lastName: 'Deshpande',
      image: 'assets/images/frequent/ramshankar.png',
      upi: 'ramshankardeshpande@okaxis',
      exchanges: '345',
      paybacks: '543',
      dues: '321',
      days: '4',
      amount: '421',
    ),
  ];

  List<Friend> _friend = [
    Friend(
      firstName: 'Ananya',
      lastName: 'Rao',
      image: 'assets/images/friend/ananya.png',
      upi: 'ananyarao@oksbi',
      exchanges: '453',
      paybacks: '322',
      dues: '323',
      days: '7',
      amount: '3,332',
    ),
    Friend(
      firstName: 'Rajashi',
      lastName: 'Prakash',
      image: 'assets/images/friend/rajashi.png',
      upi: 'rajashiprakash@okaxis',
      exchanges: '534',
      paybacks: '324',
      dues: '532',
      days: '3',
      amount: '800',
    ),
    Friend(
      firstName: 'Harshada',
      lastName: 'Nikam',
      image: 'assets/images/friend/harshada.png',
      upi: 'harshadanikam@oksbi',
      exchanges: '523',
      paybacks: '342',
      dues: '221',
      days: '4',
      amount: '250',
    ),
    Friend(
      firstName: 'John',
      lastName: 'Born',
      image: 'assets/images/friend/john.png',
      upi: 'johnborn@oksbi',
      exchanges: '344',
      paybacks: '566',
      dues: '245',
      days: '6',
      amount: '50',
    ),
  ];

  List<Friend> get recent {
    return [..._recent];
  }

  List<Friend> get frequent {
    return [..._frequent];
  }

  List<Friend> get friend {
    return [..._friend];
  }
}
